# This file describes a blueprint for use in Crafter Studio

# The version of this type of this file
descriptorVersion: 1

# Describe the blueprint
blueprint:
  id: org.craftercms.blueprint.empty
  name: MagNews Blueprint
  tags: blueprint,website
  version:
    major: 1
    minor: 0
    patch: 0
  description: |
    Simple news website blueprint
  website:
    name: MagNews Blueprint
    url: https://craftercms.org
  media:
    screenshots:
      - screenshot:
          title: Home Page
          description: Screenshot of the homepage
          url: /studio/static-assets/images/blueprints/magnews/bp_magnews.png
    developer:
      company:
        name: Russ Danner
        email: russ.danner@craftersoftware.com
        url: https://craftersoftware.com/
  build:
    id: cafebabe4e6a24b5e0481d6ba87901d0b02716c8
    date: 2019-05-23T00:00:00Z
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  craftercmsVersionsSupported:
    - version: 3.1.0
  searchEngine: Elasticsearch
